apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-tmux-proper
  namespace: ai-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-tmux-proper
  template:
    metadata:
      labels:
        app: k8s-tmux-proper
    spec:
      containers:
      - name: k8s-tmux
        image: k8s-tmux:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7681
        volumeMounts:
        - name: k8s-tmux-storage
          mountPath: /mnt/k8s-tmux
        - name: wiredquill-storage
          mountPath: /mnt/WiredQuill
        env:
        - name: TERM
          value: "xterm-256color"
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 512Mi
      volumes:
      - name: k8s-tmux-storage
        persistentVolumeClaim:
          claimName: k8s-tmux-k8s-tmux-pvc
      - name: wiredquill-storage
        persistentVolumeClaim:
          claimName: k8s-tmux-wiredquill-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-tmux-proper-service
  namespace: ai-dev
spec:
  selector:
    app: k8s-tmux-proper
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7681
  type: LoadBalancer