apiVersion: v2
name: k8s-tmux
description: A web-accessible tmux-based development environment for AI model interactions
type: application
version: 0.1.16
appVersion: "latest"
home: https://github.com/wiredquill/k8s-tmux
sources:
  - https://github.com/wiredquill/k8s-tmux
maintainers:
  - name: WiredQuill
    email: erin@suse.com
keywords:
  - tmux
  - development
  - ai
  - terminal
  - ttyd
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: ai-dev
  catalog.cattle.io/release-name: k8s-tmux
