apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName | default (include "k8s-tmux.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-tmux.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8s-tmux.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-tmux.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-tmux.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        env:
        - name: TERM
          value: {{ .Values.env.TERM | quote }}
        volumeMounts:
        {{- if .Values.mounts.k8sTmux.enabled }}
        - name: k8s-tmux-nfs
          mountPath: /mnt/k8s-tmux
        {{- end }}
        {{- if .Values.mounts.wiredQuill.enabled }}
        - name: wiredquill-nfs
          mountPath: /mnt/WiredQuill
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: app-storage
          mountPath: /mnt/storage
        {{- end }}
      volumes:
      {{- if .Values.mounts.k8sTmux.enabled }}
      - name: k8s-tmux-nfs
        nfs:
          server: {{ .Values.mounts.k8sTmux.nfs.server }}
          path: {{ .Values.mounts.k8sTmux.nfs.path }}
      {{- end }}
      {{- if .Values.mounts.wiredQuill.enabled }}
      - name: wiredquill-nfs
        nfs:
          server: {{ .Values.mounts.wiredQuill.nfs.server }}
          path: {{ .Values.mounts.wiredQuill.nfs.path }}
      {{- end }}
      {{- if .Values.persistence.enabled }}
      - name: app-storage
        persistentVolumeClaim:
          claimName: {{ include "k8s-tmux.fullname" . }}-storage-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
