{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-tmux.fullname" . }}-storage-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-tmux.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- else }}
  storageClassName: ""
  {{- end }}
{{- end }}
