name: Build Container

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'tmux.conf'
      - 'init.sh'
      - '.github/workflows/build.yaml'
  pull_request:
    paths:
      - 'Dockerfile'
      - 'tmux.conf'
      - 'init.sh'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install buildctl
      run: |
        curl -L https://github.com/moby/buildkit/releases/latest/download/buildkit-v0.12.5.linux-amd64.tar.gz | tar xz -C /tmp
        sudo mv /tmp/bin/buildctl /usr/local/bin/buildctl
        chmod +x /usr/local/bin/buildctl

    - name: Login to Container Registry
      if: github.event_name != 'pull_request'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,prefix=sha-

    - name: Build and push using wq-prod buildkit
      env:
        BUILDKIT_HOST: tcp://10.0.10.120:1234
      run: |
        echo "Using buildkit at: $BUILDKIT_HOST"
        
        # Get the first tag for the image name
        IMAGE_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
        echo "Building image: $IMAGE_TAG"
        
        if [[ "${{ github.event_name }}" != "pull_request" ]]; then
          # Build and push to registry
          buildctl build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=. \
            --output type=image,name=$IMAGE_TAG,push=true \
            --export-cache type=inline
        else
          # Build only for PR
          buildctl build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=.
        fi